### ISSUE TITLE
Do something to balance out the cognitive load of doing OSS

### ISSUE THREAD

**Issue by alloy** [segiddins/Life#13]
Sometimes it seems like everything is grim, the same shit every day. This is a very common issue with doing OSS and dealing with people. The best :pill: is some of that old-school perspective.

![](http://media4.giphy.com/media/svw5mZJdFB41G/giphy.gif)

Go sign-up for something that has nothing to do with computers, involves other people, people that don’t necessarily have anything to do with tech, and is outside of places you know. E.g. https://outdooradventureclub.com

**Comment by segiddins** [comment]
I've taken up running the past couple of months. And lots of homework. And quit CocoaPods. So I think I deserve to close this now :)

**Comment by alloy** [comment]
👌
